Remove node 18 from test runner due to instability
This should prevent the error:

```

  FetchError: request to http://localhost:9876/context.html?bypass-es-dev-server failed, reason: connect ECONNREFUSED ::1:9876
      at ClientRequest.<anonymous> (/home/runner/work/Fore/Fore/node_modules/node-fetch/lib/index.js:1491:11)
      at ClientRequest.emit (node:events:513:28)
      at Socket.socketErrorListener (node:_http_client:496:9)
      at Socket.emit (node:events:513:28)
      at emitErrorNT (node:internal/streams/destroy:151:8)
      at emitErrorCloseNT (node:internal/streams/destroy:116:3)
      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
	  ```